---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backpack-gui
spec:
  replicas: {{ required ".Values.gui.replicas must be set" .Values.gui.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backpack-gui
  template:
    metadata:
      labels:
        app: backpack-gui
      annotations:
        backpack/version: {{ .Values.gui.version }}
    spec:
      containers:
        - image: ghcr.io/linus-berg/backpack/gui:{{ required ".Values.gui.version must be set" .Values.gui.version }} 
          name: backpack-gui
          ports:
          - containerPort: 80
