apiVersion: v1
kind: ConfigMap
metadata:
  name: common-env-config
data:
  LOGGING__LOGLEVEL__DEFAULT: {{ required ".Values.backpack.log.level must be set" .Values.backpack.log.level | quote }}
  BP_RABBIT_MQ_HOST: {{ required ".Values.rabbitmq.host must be set" .Values.rabbitmq.host | quote }}
  BP_RABBIT_MQ_USER: {{ required ".Values.rabbitmq.user must be set" .Values.rabbitmq.user | quote }}
  BP_RABBIT_MQ_PASS: {{ required ".Values.rabbitmq.pass must be set" .Values.rabbitmq.pass | quote }}
{{- if .Values.otel }}
  BP_OTEL_HOST: {{ .Values.otel.host | quote }}
{{- end }}
{{- if .Values.no_proxy }}
  NO_PROXY: {{ (join "," .Values.no_proxy) | quote }}
  no_proxy: {{ (join "," .Values.no_proxy) | quote }}
{{- end }}
{{- if .Values.http_proxy }}
  HTTP_PROXY: {{ .Values.http_proxy | quote }}
  HTTPS_PROXY: {{ .Values.http_proxy | quote }}
  http_proxy: {{ .Values.http_proxy | quote }}
  https_proxy: {{ .Values.http_proxy | quote }}
{{- end }}
{{- if .Values.ca_certificates }}
  ca-certificates.crt: {{ .Values.ca_certificates | quote }}
{{- end }}
