---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backpack-gateway
spec:
  replicas: {{ required ".Values.gateway.replicas must be set" .Values.ingestion.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backpack-gateway
  template:
    metadata:
      labels:
        app: backpack-gateway
      annotations:
        backpack/version: {{ .Values.backpack.version }}
        checksum/config: {{ include (print $.Template.BasePath "/common-configmap.yaml") . | sha256sum }}
        checksum/gateway-config: {{ include (print $.Template.BasePath "/gateway/gateway-configmap.yaml") . | sha256sum }}
    spec:
      {{- if $.Values.hosts }}
      hostAliases:
        {{- range $.Values.hosts }}
        - ip: {{ .ip | quote }}
          hostnames:
          {{- range .hostnames }}
            - {{ . | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - image: ghcr.io/linus-berg/backpack/core/gateway:{{ required ".Values.backpack.version version must be set" .Values.backpack.version }} 
          name: backpack-gateway
          envFrom:
            - configMapRef:
                name: common-env-config
            - configMapRef:
                name: gateway-env-config
