---
apiVersion: v1
kind: Service
metadata:
  name: backpack-api
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.api.port }}
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: {{ .Values.api.loadBalancerIP }}
  selector:
    app: backpack-api
